# Generated by Django 5.2.4 on 2026-02-13 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_contact_id_alter_medicalrecord_id_alter_pet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('shipping_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('design', models.CharField(choices=[('Classic', 'Classic Black'), ('Sporty', 'Sporty Red'), ('Luxury', 'Luxury Gold'), ('Glow', 'Glow in Dark')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(default='Cash on Delivery', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pet.pet')),
            ],
        ),
    ]
