from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='landing'),
    path('home/', views.home, name='home'),
    path('about/', views.aboutpage, name='about'),
    path('contact/', views.contactpage, name='contact'),
    path('staff-dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff/user/<int:pk>/edit/', views.staff_edit_user, name='staff_edit_user'),
    path('staff/user/<int:pk>/delete/', views.staff_delete_user, name='staff_delete_user'),
    path('staff/users/', views.staff_users_list, name='staff_users_list'),
    path('register/', views.register, name='regi'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('how-it-works/', views.how_it_works, name='how_it_works'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile_view, name='profile'), 
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('pet/add/', views.pet_create, name='pet_create'),
    path('pet/<int:pk>/edit/', views.pet_update, name='pet_update'),
    path('pet/<int:pk>/delete/', views.pet_delete, name='pet_delete'),
    path('pet/<int:pk>/lost-mode/', views.toggle_lost_mode, name='toggle_lost_mode'),
    path('pet/<int:pk>/medical/', views.medical_records, name='medical_records'),
    path('pet/<int:pk>/qr/download/', views.download_qr, name='download_qr'),
    path('p/<slug:unique_slug>/', views.pet_detail_public, name='pet_detail_public'),
    path('profile/deactivate/', views.deactivate_account, name='deactivate_account'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-success/<int:order_id>/', views.order_success, name='order_success'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('collar-review/<int:order_id>/', views.collar_review, name='collar_review'),
    path('submit-review/', views.submit_review, name='submit_review'),
    path('all-reviews/', views.all_reviews, name='all_reviews'),
    path('order/invoice/<int:order_id>/', views.download_invoice, name='download_invoice'),
    path('pet/<int:pk>/poster/', views.generate_lost_poster, name='generate_lost_poster'),
    path('pet/<int:pk>/poster/preview/', views.poster_preview, name='poster_preview'),
    path('scan/<int:pk>/delete/', views.delete_scan, name='delete_scan'),
    path('order/<int:pk>/delete/', views.delete_order, name='delete_order'),
]